name: course-CI

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:
jobs:
  checker:
    runs-on: ubuntu:20.04
    steps:
      - name: Build Docker image
          run: |
            docker build -t checker-image .
      - name: Run docker
          id: run-checker
          run: |
            docker run checker-image -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} GITHUB_HEAD_REF=${{ GITHUB_HEAD_REF }}
      - name: Checker fail
        if: steps.run-checker.outputs.checks-failed > 0
        run: echo "Check CI summary for report" && exit 1
